import * as Dialog from "@radix-ui/react-dialog";
import { ChevronDown, Search } from "lucide-react";
import { useMemo, useState } from "react";
import Markdown, { type Components } from "react-markdown";
import { useLicensesText } from "../hooks/use-data";
import { cx } from "../lib/time";

/** One `## name@version` section of THIRD_PARTY_NOTICES.md. */
interface LicenseEntry {
  /** `name@version` as printed by the generator — unique per entry. */
  id: string;
  name: string;
  version: string;
  license: string;
  /** Fenced license text; null when the package ships no license file. */
  text: string | null;
}

/**
 * Parses the generated THIRD_PARTY_NOTICES.md (scripts/generate-notices.mjs):
 * a markdown preamble, then `## name@version` sections each carrying a
 * `License:` line and either a fenced license text or a "(No license file
 * present…)" note.
 */
function parseNotices(content: string): { preamble: string; entries: LicenseEntry[] } {
  const first = content.indexOf("\n## ");
  const preamble = (first === -1 ? content : content.slice(0, first)).replace(/^# .*\n/, "").trim();
  const rest = first === -1 ? "" : content.slice(first + 1);
  const entries: LicenseEntry[] = [];
  for (const block of rest.split(/\n(?=## )/)) {
    const id = /^## (.+)$/.exec(block.split("\n", 1)[0] ?? "")?.[1]?.trim();
    if (!id) continue;
    // The version follows the LAST "@" — scoped names carry earlier ones.
    const split = /^(.+)@([^@\s]+)$/.exec(id);
    entries.push({
      id,
      name: split?.[1] ?? id,
      version: split?.[2] ?? "",
      license: /(?:^|\n)License: (.+)/.exec(block)?.[1]?.trim() ?? "Unknown",
      text: /```\n([\s\S]*?)\n```/.exec(block)?.[1]?.trim() ?? null,
    });
  }
  return { preamble, entries };
}

/** Minimal theme-aware markdown rendering for the preamble (no code blocks there). */
const preambleComponents: Components = {
  p: ({ children }) => <p className="my-1.5 text-[11px] leading-relaxed text-ink-dim">{children}</p>,
  ul: ({ children }) => (
    <ul className="my-1.5 list-disc space-y-0.5 pl-4 text-[11px] leading-relaxed text-ink-dim">{children}</ul>
  ),
  li: ({ children }) => <li className="leading-relaxed">{children}</li>,
  strong: ({ children }) => <strong className="font-semibold text-ink">{children}</strong>,
  a: ({ href, children }) => (
    <a
      href={href}
      onClick={(event) => {
        event.preventDefault();
        if (href?.startsWith("http")) void window.promptBuilder.app.openExternal(href).catch(() => {});
      }}
      className="cursor-pointer text-accent underline-offset-2 hover:underline"
    >
      {children}
    </a>
  ),
  code: ({ children }) => (
    <code className="rounded border border-line bg-raised px-1 py-px font-mono text-[10px] text-ink-dim">{children}</code>
  ),
  hr: () => <hr className="my-2 border-line" />,
};

/**
 * In-app viewer for the bundled third-party notices (THIRD_PARTY_NOTICES.md,
 * generated by scripts/generate-notices.mjs). Searchable, collapsible list —
 * one row per bundled package, license text expands in place. Opened from the
 * About dialog and Settings → About.
 */
export function LicensesDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const { data, isPending, isError } = useLicensesText(open);
  const [query, setQuery] = useState("");
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const parsed = useMemo(() => (data !== undefined ? parseNotices(data) : null), [data]);
  const entries = parsed?.entries ?? [];
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return entries;
    return entries.filter((entry) => `${entry.name}@${entry.version} ${entry.license}`.toLowerCase().includes(q));
  }, [entries, query]);

  return (
    <Dialog.Root open={open} onOpenChange={onOpenChange}>
      <Dialog.Portal>
        <Dialog.Overlay className="pb-overlay fixed inset-0 z-40 bg-black/60" />
        <Dialog.Content
          aria-describedby={undefined}
          className="pb-dialog fixed left-1/2 top-1/2 z-50 flex h-[calc(100vh-4rem)] w-[calc(100vw-4rem)] max-w-2xl -translate-x-1/2 -translate-y-1/2 flex-col overflow-hidden rounded-xl border border-line-strong bg-panel p-0 shadow-2xl shadow-black/50 focus:outline-none"
        >
          <div className="border-b border-line px-5 py-4">
            <Dialog.Title className="text-[15px] font-semibold tracking-tight text-ink">Open Source Licenses</Dialog.Title>
            <p className="mt-0.5 text-[12px] text-ink-dim">
              PromptBranch is open source (MIT) and bundles {entries.length > 0 ? entries.length : "…"} third-party
              packages under these licenses.
            </p>
            <div className="relative mt-3">
              <Search
                size={12}
                className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-ink-faint"
              />
              <input
                aria-label="Search licenses"
                placeholder="Search packages or licenses…"
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                className="w-full rounded-md border border-line bg-app py-1.5 pl-7 pr-2.5 text-[12px] text-ink placeholder:text-ink-faint focus:border-accent/60 focus:outline-none focus:ring-1 focus:ring-accent/40"
              />
            </div>
          </div>

          <div className="min-h-0 flex-1 overflow-y-auto px-3 py-3">
            {isPending && <p className="px-2 text-[12px] text-ink-faint">Loading notices…</p>}
            {isError && (
              <p className="px-2 text-[12px] text-ink-faint">Could not load the third-party notices file.</p>
            )}
            {parsed && (
              <>
                <div className="rounded-lg border border-line bg-app px-3.5 py-3">
                  <Markdown components={preambleComponents}>{parsed.preamble}</Markdown>
                </div>
                <ul className="mt-2">
                  {filtered.map((entry) => {
                    const expanded = expandedId === entry.id;
                    return (
                      <li key={entry.id}>
                        <button
                          type="button"
                          aria-expanded={expanded}
                          onClick={() => setExpandedId(expanded ? null : entry.id)}
                          className="flex w-full items-center gap-2 rounded-md px-2.5 py-1.5 text-left transition-colors hover:bg-hover"
                        >
                          <ChevronDown
                            size={12}
                            className={cx("shrink-0 text-ink-faint transition-transform", !expanded && "-rotate-90")}
                          />
                          <span className="min-w-0 truncate font-mono text-[12px] text-ink">{entry.name}</span>
                          {entry.version && (
                            <span className="shrink-0 font-mono text-[11px] text-ink-faint">@{entry.version}</span>
                          )}
                          <span className="ml-auto shrink-0 rounded border border-line bg-raised px-1.5 py-px font-mono text-[10px] text-ink-dim">
                            {entry.license}
                          </span>
                        </button>
                        {expanded && (
                          <div className="mx-2 mb-2 ml-8 max-h-72 overflow-y-auto rounded-md border border-line bg-app">
                            {entry.text ? (
                              <pre className="whitespace-pre-wrap p-3 font-mono text-[10px] leading-relaxed text-ink-dim">
                                {entry.text}
                              </pre>
                            ) : (
                              <p className="p-3 text-[11px] text-ink-faint">
                                No license file ships with this package; its declared license ({entry.license}) applies.
                              </p>
                            )}
                          </div>
                        )}
                      </li>
                    );
                  })}
                </ul>
                {filtered.length === 0 && (
                  <p className="px-2 py-6 text-center text-[12px] text-ink-faint">
                    No packages match “{query.trim()}”.
                  </p>
                )}
              </>
            )}
          </div>

          <div className="flex items-center justify-between border-t border-line px-5 py-2.5">
            <p className="text-[11px] text-ink-faint">
              Showing {filtered.length} of {entries.length} packages
            </p>
            <Dialog.Close className="rounded-md border border-line px-3 py-1.5 text-[13px] text-ink-dim transition-colors hover:bg-hover hover:text-ink">
              Close
            </Dialog.Close>
          </div>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
  );
}
