import fs from "node:fs";
import path from "node:path";
import { app, nativeImage, type NativeImage } from "electron";

/**
 * Template (monochrome) icons for the native app-menu items. macOS tints
 * templates to match the menu bar in light/dark mode; the Windows/Linux menu
 * bars draw no item icons, so attaching them there is a harmless no-op.
 * Generated by scripts/generate-menu-icons.mjs (part of the `icons` script)
 * and shipped as extraResources — in dev checkouts they sit in build/.
 */
export interface MenuIcons {
  about?: NativeImage;
  checkUpdates?: NativeImage;
  settings?: NativeImage;
}

export function loadMenuIcons(): MenuIcons {
  const candidates = [
    path.join(process.resourcesPath, "menu-icons"),
    path.join(app.getAppPath(), "build", "menu-icons"),
  ];
  const dir = candidates.find((candidate) => fs.existsSync(path.join(candidate, "about.png")));
  if (!dir) {
    console.log("[main] menu icons not found (run `pnpm --filter @promptbranch/desktop icons`) — text-only menu");
    return {};
  }
  const load = (name: string): NativeImage | undefined => {
    // Picks up the @2x variant automatically for retina.
    const image = nativeImage.createFromPath(path.join(dir, `${name}.png`));
    if (image.isEmpty()) return undefined;
    image.setTemplateImage(true);
    return image;
  };
  const icons: MenuIcons = {
    about: load("about"),
    checkUpdates: load("check-updates"),
    settings: load("settings"),
  };
  console.log(`[main] menu icons loaded from ${dir}`);
  return icons;
}
